# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c295d7496fff436a1b7e3a17d43c9d219f7d0f0e941b6e3ad89cf84d31132e671ade87ea0b21335ebbd5ba1cd30f21aa3b312dd21031c205b3a1afa20088bfb

test:
  secret_key_base: 8cae13f877a166f3510f7dedbfa39960531a6270028ada9a7532206f2ab86d674341e7a91f76184a2d678210ecefa31a0c3f4cdc8382a81266e82ad44b708ce7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
